name = "tamago"
version = "0.1.0"
defaultTargets = ["Tamago", "Tamago.Spec", "Tamago.Proof"]
buildDir = "artifacts/lean"

[[require]]
name = "verity"
git = "https://github.com/lfglabs-dev/verity.git"
rev = "8b6b8c21fac15c56acb8812207a06c9cc168816b"

[[lean_lib]]
name = "Tamago"
srcDir = "verity/src"

[[lean_lib]]
name = "Tamago.Common"
srcDir = "verity/common"

[[lean_lib]]
name = "Tamago.Spec"
srcDir = "verity/spec"

[[lean_lib]]
name = "Tamago.Proof"
srcDir = "verity/proof"

[[lean_exe]]
name = "verity-compiler"
root = "Compiler.Main"
srcDir = ".lake/packages/verity"
supportInterpreter = true
